version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/
    depends_on:
      - mariadb
    restart: on-failure
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - "443:443"
  
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/danis/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/danis/data/mariadb

networks:
  inception:
    driver: bridge